extends CenterContainer


# Called when the node enters the scene tree for the first time.
func _ready():
	$cards/card_1/AnimationPlayer.play("select")
	await $cards/card_1/AnimationPlayer.animation_finished
	$cards/card_1/AnimationPlayer.play("deselect")
	$cards/card_2/AnimationPlayer.play("select")
	await $cards/card_1/AnimationPlayer.animation_finished
	$cards/card_2/AnimationPlayer.play("deselect")
	$cards/card_3/AnimationPlayer.play("select")
	await $cards/card_2/AnimationPlayer.animation_finished
	$cards/card_3/AnimationPlayer.play("deselect")
	await $cards/card_3/AnimationPlayer.animation_finished
	$cards/card_1/AnimationPlayer.play("select")
	await $cards/card_1/AnimationPlayer.animation_finished
	$cards/card_1/AnimationPlayer.play("take")
	$cards/card_2/AnimationPlayer.play("unshuffle")
	$cards/card_3/AnimationPlayer.play("shuffle")
	await $cards/card_3/AnimationPlayer.animation_finished
	
	for card in $cards.get_children():
		card.get_child(1).play("RESET")
		
	$cards/card_2/AnimationPlayer.queue("select")
	await $cards/card_2/AnimationPlayer.animation_finished
	$cards/card_2/AnimationPlayer.play("take")
	$cards/card_3/AnimationPlayer.play("unshuffle")
	$cards/card_1/AnimationPlayer.play("shuffle")
	await $cards/card_1/AnimationPlayer.animation_finished
	
	for card in $cards.get_children():
		card.get_child(1).play("RESET")
		
	$cards/card_3/AnimationPlayer.queue("select")
	await $cards/card_3/AnimationPlayer.animation_finished
	$cards/card_3/AnimationPlayer.play("take")
	$cards/card_1/AnimationPlayer.play("unshuffle")
	$cards/card_2/AnimationPlayer.play("shuffle")
	await $cards/card_2/AnimationPlayer.animation_finished
	
	$sticky_notes.show()
	
	for card in $sticky_notes.get_children():
		card.get_child(1).play("post")
	
	await $sticky_notes/sticky_note_1/AnimationPlayer.animation_finished
	
	$sticky_notes/sticky_note_1/AnimationPlayer.play("select")
	await $sticky_notes/sticky_note_1/AnimationPlayer.animation_finished
	$sticky_notes/sticky_note_1/AnimationPlayer.play("deselect")
	$sticky_notes/sticky_note_2/AnimationPlayer.play("select")
	await $sticky_notes/sticky_note_2/AnimationPlayer.animation_finished    
	$sticky_notes/sticky_note_2/AnimationPlayer.play("deselect")
	$sticky_notes/sticky_note_3/AnimationPlayer.play("select")
	await $sticky_notes/sticky_note_3/AnimationPlayer.animation_finished    
	$sticky_notes/sticky_note_3/AnimationPlayer.play("deselect")
	$sticky_notes/sticky_note_4/AnimationPlayer.play("select")
	await $sticky_notes/sticky_note_4/AnimationPlayer.animation_finished    
	$sticky_notes/sticky_note_4/AnimationPlayer.play("deselect")
	$sticky_notes/sticky_note_1/AnimationPlayer.play("select")
	await get_tree().create_timer(1).timeout
	$sticky_notes/sticky_note_1/AnimationPlayer.play("pick")
	$sticky_notes/sticky_note_2/AnimationPlayer.play("shuffle")
	$sticky_notes/sticky_note_3/AnimationPlayer.play("unshuffle")
	$sticky_notes/sticky_note_4/AnimationPlayer.play("unshuffle")
	
	await $sticky_notes/sticky_note_2/AnimationPlayer.animation_finished    
	
	for card in $sticky_notes.get_children():
		card.get_child(1).play("post")
	
	await $sticky_notes/sticky_note_1/AnimationPlayer.animation_finished
	
	$sticky_notes/sticky_note_2/AnimationPlayer.play("select")
	await get_tree().create_timer(1).timeout
	$sticky_notes/sticky_note_2/AnimationPlayer.play("pick")
	$sticky_notes/sticky_note_3/AnimationPlayer.play("shuffle")
	$sticky_notes/sticky_note_4/AnimationPlayer.play("unshuffle")
	$sticky_notes/sticky_note_1/AnimationPlayer.play("unshuffle")

	await $sticky_notes/sticky_note_3/AnimationPlayer.animation_finished

	for card in $sticky_notes.get_children():
		card.get_child(1).play("post")
	
	await $sticky_notes/sticky_note_1/AnimationPlayer.animation_finished
	
	$sticky_notes/sticky_note_3/AnimationPlayer.play("select")
	await get_tree().create_timer(1).timeout
	$sticky_notes/sticky_note_3/AnimationPlayer.play("pick")
	$sticky_notes/sticky_note_4/AnimationPlayer.play("shuffle")
	$sticky_notes/sticky_note_1/AnimationPlayer.play("unshuffle")
	$sticky_notes/sticky_note_2/AnimationPlayer.play("unshuffle")
	
	await $sticky_notes/sticky_note_4/AnimationPlayer.animation_finished
	
	for card in $sticky_notes.get_children():
		card.get_child(1).play("post")
	
	await $sticky_notes/sticky_note_1/AnimationPlayer.animation_finished
	
	$sticky_notes/sticky_note_4/AnimationPlayer.play("select")
	await get_tree().create_timer(1).timeout
	$sticky_notes/sticky_note_4/AnimationPlayer.play("pick")
	$sticky_notes/sticky_note_1/AnimationPlayer.play("shuffle")
	$sticky_notes/sticky_note_2/AnimationPlayer.play("unshuffle")
	$sticky_notes/sticky_note_3/AnimationPlayer.play("unshuffle")
